### ISSUE TITLE
Temporary files not being removed with `setKeepGeneratedTempFiles(false)` 

### ISSUE THREAD

**Issue by jasalt** [jasalt/phel-wp-plugin#12]
`phel-config.php` config option `->setKeepGeneratedTempFiles(false)` does not seem to have effect with the plugin. Few hundred temporary __phelXXXXXX files keep getting added in `/tmp` after every request. 

To reproduce:
```
docker compose down -v  # trash container it it already exists 
docker compose up
docker compose exec wordpress ls /tmp | wc -l  # count files in /tmp
# -> 253
```

Access the development site at http://localhost:8081/ and see again:
```
docker compose exec wordpress ls /tmp | wc -l`
# -> 505
```

Maybe cleanup is not getting triggered as it should.

The amount gets quite large quickly. Cleaning them up with `find /tmp/ -maxdepth 1 -type f -name "__phel*" -delete` running in cron as workaround.

**Comment by Chemaclass** [comment]
Can you open an issue on phel-lang project and point to this one as well. It might be an issue on phel-lang project itself 🤔 I will try to find time this week to investigate this

**Comment by jasalt** [comment]
Fix confirmed working, removed `*/15 * * * * find /tmp/ -maxdepth 1 -type f -name "__phel*" -delete` from server crontab :), thank's @Chemaclass,.
