### ISSUE TITLE
docker-compose.yml `working_dir` directive breaks initial `docker compose up`

### ISSUE THREAD

**Issue by jasalt** [jasalt/phel-wp-plugin#8]
@Chemaclass noted issue with your latest commit related to https://github.com/jasalt/phel-wp-plugin/pull/3 adding following in `docker-compose.yml`, which makes container fail on initial startup:

```
working_dir: /bitnami/wordpress/wp-content/plugins/phel-wp-plugin
```

This leads to:

```
mariadb-1    | 2024-11-18 12:48:49 0 [Note] InnoDB: Buffer pool(s) load completed at 241118 12:48:49
wordpress-1  | wordpress 12:48:50.32 INFO  ==> Trying to connect to the database server
wordpress-1  | Error: 'wp-config.php' not found.
wordpress-1  | Either create one manually or use `wp config create`.
wordpress-1 exited with code 1
```

To see it, drop the volumes and recreate the whole thing again (in 347f101 or b823ea6):
```
docker compose down -v
docker compose up
```

I think it's maybe related to similar behavior I tried to workaround earlier, that you cannot refer to such path in docker-compose.yml that gets populated by the container image scripts on init, or else those fail. 

I'll comment that for now (https://github.com/jasalt/phel-wp-plugin/commit/4a38d7c7ba4291175c0736e76b1e39d5d7c10796) before there is workaround. It works if the comment is removed after container has been created earlier though so easy to go unnoticed.

**Comment by Chemaclass** [comment]
we can remove that `working_dir`. I added because I thought it would not affect negatively anything, but don't hesitate to remove it :)

**Comment by jasalt** [comment]
Removed https://github.com/jasalt/phel-wp-plugin/commit/5688850104aae25f73e96b09b0233d1dad8e6730, can be added back if there is decent way to make it work and it's useful.
